apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv-spain-schedule-collector-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
