apiVersion: v1
kind: Service
metadata:
  name: {{ include "tv-spain-schedule-collector.fullname" . }}
  labels:
    {{- include "tv-spain-schedule-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "tv-spain-schedule-collector.selectorLabels" . | nindent 4 }}
